#compose traefik

version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
#    environment:
 #     - CF_DNS_API_TOKEN=SphaEJZG9ddmwuH4APExg53GA904dbNRT_L7A9AQ
    restart: always
  #  command:
   #   - --api.dashboard=true
    #  - --providers.docker=true
    #  - --providers.docker.exposedbydefault=false
    #  - --entrypoints.web.address=:80
    #  - --entrypoints.websecure.address=:443
#     - --certificatesresolvers.le.acme.httpchallenge=true
#      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    #  - --certificatesresolvers.le.acme.dnschallenge=true
    #  - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
    #  - --certificatesresolvers.le.acme.email=mobinjhantigh@gmail.com
    #  - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - web

networks:
  web:
    external: true
